spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    version: 2.1.0
    command: pay
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    orderType: other
    returnUrl: ${APP_DOMAIN}/payment-form/vnPayReturn

  payOs:
    client_id: ${PAYOS_CLIENT_ID}
    api_key: ${PAYOS_API_KEY}
    checksum_key: ${PAYOS_CHECKSUM_KEY}
    cancel_url: ${APP_DOMAIN}/cancel
    return_url: ${APP_DOMAIN}/home
    bankId: 970422

cloudinary:
  cloud_name: ${CLOUD_NAME_CLOUDINARY}
  api_key: ${API_KEY_CLOUDINARY}
  api_secret: ${API_SECRET_CLOUDINARY}